version: "3.9"
services:
  monitor:
    build: .
    network_mode: host  # Necessário para acessar interfaces de rede do host
    cap_add:
      - NET_ADMIN  # Criação de interfaces virtuais, se necessário
      - NET_RAW    # Permite uso de sockets RAW
    environment:
      - LOG_DIR=/logs
    volumes:
      - ./logs:/logs
    command: ["python", "src/monitor.py", "tun0"] 